# -*- coding: utf-8 -*-
"""lisacode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JvVwJWobR5SczIqIpZsNoGoKF8Jezsmv
"""

name = input('Введите имя, ')
print ('Привет, ' , name)